# Generated by Django 3.1.4 on 2021-04-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201213_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='translate_mode',
            field=models.IntegerField(choices=[(0, 'Full editor'), (1, 'Zen mode')], default=1, verbose_name='Translation editor mode'),
        ),
    ]
