# Generated by Django 3.1.4 on 2021-04-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210403_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='zen_mode',
            field=models.IntegerField(choices=[(0, 'Top to bottom'), (1, 'Side by side')], default=1, verbose_name='Zen editor mode'),
        ),
    ]
